micronaut:
  application.name: rawdata-converter-app-bong
  server.port: 28086

endpoints:
  prometheus:
    sensitive: false

oauth:
  server-url: https://keycloak.staging-bip-app.ssb.no/auth/realms/ssb/protocol/openid-connect

rawdata.client:
  provider: filesystem
  local-temp-folder: temp
  avro-file:
    max.seconds: 3600
    max.bytes: 10485760
    sync.interval: 500000
  filesystem:
    storage-folder: ./rawdata-store
    #storage-folder: ../localenv/rawdatastore
  listing:
    min-interval-seconds: 0

rawdata.converter:
  active-by-default: true
  dryrun: false
  storage-type: local
  storage-root: file://../localenv/datastore
  storage-path: /kilde/ng/bong/raadata/v1
  storage-version: 1598553650000
  service-account-key-file: ../localenv/auth/gcs/dev-sirius/gcs_credentials.json
  topic: bong-ng-test
  window-max-records: 1000
  window-max-time-in-seconds: 60
  initial-position: LAST
  schema-metrics-enabled: true
  dataset-type: BOUNDED

  dataset-meta:
    valuation: INTERNAL
    type: BOUNDED
    should-publish-meta: false
    data-access-service:
      host: localhost
      port: 4242
    metadata-distributor-service:
      host: localhost
      port: 2424
      project-id: local
      topic: metadata-distributor-dataset-updates #FIXME

logger:
  levels:
    no.ssb.rawdata.converter.core: INFO

#rawdata.converter.app.bong:
#  schema-file-bong: schema/ng-bong.avsc

