package no.ssb.rawdata.converter.app.bong;

import no.ssb.dapla.dataset.api.Type;
import no.ssb.rawdata.api.RawdataConsumer;
import no.ssb.rawdata.converter.core.RawdataConverter;
import no.ssb.rawdata.converter.core.RawdataConverterConfig;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * The rawdata used in this test can be generated by using the {@link BongRawdataPublisherTest}
 */
public class SomeshopBongConverterJobITest extends BongConverterJobIntegrationTestBase {

    @Test
    @Disabled
    public void testConverterJobExecutor() {
        RawdataConverterConfig rawdataConverterConfig = new RawdataConverterConfig();
        rawdataConverterConfig.setActiveByDefault(true);
        rawdataConverterConfig.setDryrun(false);
        rawdataConverterConfig.setDebug(true);
        rawdataConverterConfig.setTopic("some-shop");
        rawdataConverterConfig.setStorageType("local");
        rawdataConverterConfig.setStorageRoot(uriStringOf("../localenv/datastore"));
        rawdataConverterConfig.setStoragePath("/kilde/someshop/bong/2017-01/raadata/test");
        rawdataConverterConfig.setStorageVersion(1598553650000L);
        rawdataConverterConfig.setInitialPosition("FIRST");
        rawdataConverterConfig.setWindowMaxRecords(1000);
        rawdataConverterConfig.setSchemaMetricsEnabled(false);
        rawdataConverterConfig.setDatasetType(Type.BOUNDED);

        BongRawdataConverterConfig bongRawdataConverterConfig = new BongRawdataConverterConfig();
        bongRawdataConverterConfig.setSchemaFileBong("schema/ng-bong.avsc");
        bongRawdataConverterConfig.getCsvSettings().put("delimiters", "|");
        RawdataConverter converter = new BongRawdataConverter(bongRawdataConverterConfig);

        RawdataConsumer rawdataConsumer = rawdataConsumerFactory.rawdataConsumer(rawdataConverterConfig);
        jobScheduler.start(rawdataConverterConfig, converter, rawdataConsumer);
    }

}
